import os

USER_HOME = os.path.expanduser("~")
EREADER_DIR = os.path.join(USER_HOME, "ereader")
DISPLAY_WIDTH = 250
DISPLAY_HEIGHT = 122
MARGIN_TOP = 4
MARGIN_BOTTOM = 4
MARGIN_LEFT = 6
MARGIN_RIGHT = 6
FONT_PATH = EREADER_DIR + "/fonts/LiberationMono-Regular.ttf"
FONT_SIZE = 10
FILES_PER_SCREEN = 8
MAX_FILENAME_LENGTH = 30
HOLD_THRESHOLD = 1.0
MULTI_CLICK_WINDOW = 0.5
PARTIAL_REFRESH_LIMIT = 10
LIBRARY_PATH = EREADER_DIR + "/library"
CACHE_DIR = EREADER_DIR + "/cache"
FONTS_DIR = EREADER_DIR + "/fonts"
SUPPORTED_EXTENSIONS = {".txt", ".epub", ".pdf"}
PDF_DPI = 150
IDLE_TIMEOUT = 60
PISUGAR_HOST = "127.0.0.1"
PISUGAR_PORT = 8421
DEBUG_MODE = False
MOCK_DISPLAY_PATH = "debug_output.png"
